In [1]:
import numpy as np
from tqdm import tqdm as _tqdm


def tqdm(*args, **kwargs):
    # Safety, do not overflow buffer
    return _tqdm(*args, **kwargs, mininterval=1)

In [2]:
from riverswim import RiverswimEnv
env = RiverswimEnv()
# Lets see what this is
# ?env

In [3]:
# Take a moment to figure out what P represents.
# Note that this is a deterministic environment.
# What would a stochastic environment look like?
env.P

{0: {0: [(1.0, 0, 0.05, 0)], 1: [(0.6, 0, 0, 0), (0.4, 1, 0, 0)]},
 1: {0: [(1.0, 0, 0, 0)],
  1: [(0.05, 0, 0, 0), (0.55, 1, 0, 0), (0.4, 2, 0, 0)]},
 2: {0: [(1.0, 1, 0, 0)],
  1: [(0.05, 1, 0, 0), (0.55, 2, 0, 0), (0.4, 3, 0, 0)]},
 3: {0: [(1.0, 2, 0, 0)],
  1: [(0.05, 2, 0, 0), (0.55, 3, 0, 0), (0.4, 4, 0, 0)]},
 4: {0: [(1.0, 3, 0, 0)],
  1: [(0.05, 3, 0, 0), (0.55, 4, 0, 0), (0.4, 5, 0, 0)]},
 5: {0: [(1.0, 4, 0, 0)], 1: [(0.6, 5, 1, 0), (0.4, 4, 1, 0)]}}

# policy iteration

In [4]:
from dp import policy_iteration, value_iteration

In [5]:
# Let's see what it does
policy, v = policy_iteration(env)
print("Policy Probability Distribution:")
print(policy)
print("")

print("Value Function:")
print(v)
print("")

Policy Probability Distribution:
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]

Value Function:
[0.54929387 0.79380008 1.17642425 1.74494816 2.58737575 3.83556129]



# value iteration

In [6]:
# Oh let's test again
# Let's see what it does
policy, v = value_iteration(env)
print("Policy Probability Distribution:")
print(policy)
print("")

print("Value Function:")
print(v)
print("")

Policy Probability Distribution:
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]

Value Function:
[0.54932344 0.7938261  1.17644767 1.74496939 2.58739504 3.83557883]

